apiVersion: v1
kind: Service
metadata:
  name: "{{ include "postgres.fullname" . }}-replica"
  namespace: {{ include "postgres.namespace" . }}
  labels:
    replica: "true"
{{- include "postgres.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  selector:
    role: replica
{{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      name: sql
    - port: 8008
      name: patroni