apiVersion: alpha.postgres.local/v1alpha1
kind: Postgres
metadata:
  name: postgres-version1
  namespace: mon
spec:
  name: version1
  namespace: mon
  replicas: 2
  sidecar:
    enable: false
  storage:
    capacity: 5Gi
  client:
    name: dGVzdHVzZXI=
    password:  c3Ryb25ncGFzc3dvcmQ=
    database: ZGF0YWJhc2Ux

  config:
    hba:
      - host database1 testuser 0.0.0.0/0 trust

  backup:
    enable: true
    platform:
      name: gcp
      secret:
        name: postgres-walg-test1
        key: key.json
      bucketName: gs://postgres-default-bb-test-main/test