apiVersion: alpha.postgres.local/v1alpha1
kind: Postgres
metadata:
  name: postgres-testv3
  namespace: mon
spec:
  name: mon2
  namespace: mon
  replicas: 2
  labels:
    key: val
  sidecar:
    enable: true
  storage:
    capacity: 10Gi
  client:
    name: Q2xpZW50
    password:  cGFzc3dvcmQxMjM=
    database: bXlfZGF0YWJhc2U=

  backup:
    enable: true
    platform:
      name: gcp
      secret:
        name: postgres-walg-test1
        key: key.json
      bucketName: gs://postgres-default-bb-test-main/test