apiVersion: alpha.postgres.local/v1alpha1
kind: Postgres
metadata:
  name: postgres-test
  namespace: mon
spec:
  name: mon
  namespace: mon
  replicas: 2
  labels:
    key: val
  sidecar:
    enable: true
