apiVersion: v1
kind: Service
metadata:
  name: postgres-{{- .Values.name -}}-master
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
spec:
  clusterIP: "None"
  selector:
    role: master
{{- include "postgres-labels" . | indent 4 }}
  ports:
    - port: 5432
      name: sql
    - port: 8008
      name: patroni