{{- if .Values.rbac.serviceAccount.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "postgres.fullname" . }}-role"
  namespace: {{ include "postgres.namespace" . }}
  labels:
{{- include "postgres.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints","pods","services"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
{{- end }}