{{- if .Values.rbac.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "postgres.fullname" . }}-sa"
  namespace: {{ include "postgres.namespace" . }}
  labels:
{{- include "postgres.labels" . | nindent 4 }}
{{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}