apiVersion: v1
kind: Service
metadata:
  name: postgres-{{- .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
spec:
  clusterIP: "None"
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack