apiVersion: v1
kind: Secret
metadata:
  name: postgres-{{- .Values.name -}}-admin
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
data:
  replicator: "cmVwbGljYXRvcg=="
  {{- if .Values.secrets.replicator_password }}
  replicator-password: {{ .Values.secrets.replicator_password | quote | default "cmVwbGljYXRvcg==" }} 
  {{- else }}
  replicator-password: "cmVwbGljYXRvcg=="
  {{- end }}
  superuser: "cG9zdGdyZXM="
  {{- if .Values.secrets.superuser_password }}
  superuser-password: {{ .Values.secrets.superuser_password | quote | default "cG9zdGdyZXM=" }} 
  {{- else }}
  superuser-password: "cG9zdGdyZXM="
  {{- end }}