apiVersion: v1
kind: Secret
metadata:
  name: postgres-{{- .Values.name -}}-client
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
data:
  {{- if .Values.client.name }}
  user: {{ .Values.client.name | quote | default "Y2xpZW50" }} 
  {{- else }}
  user: "Y2xpZW50"
  {{- end }}
  {{- if .Values.client.password }}
  password: {{ .Values.client.password | quote | default "Y2xpZW50" }} 
  {{- else }}
  password: "Y2xpZW50"
  {{- end }}
  {{- if .Values.client.database }}
  database: {{ .Values.client.database | quote | default "Y2xpZW50" }} 
  {{- else }}
  database: "Y2xpZW50"
  {{- end }}