apiVersion: v1
kind: Secret
metadata:
  name: postgres-{{- .Values.name -}}-host
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
data:
  hostreplica: {{ printf "postgres-%s-replica.%s.svc.cluster.local"  .Values.name .Values.namespace | b64enc | quote  }}
  hostmaster: {{ printf "postgres-%s-master.%s.svc.cluster.local"  .Values.name .Values.namespace | b64enc | quote  }}
  #hostjdbc: "amRiYw=="
  port: "NTQzMg=="
 