apiVersion: v1
kind: Secret
metadata:
  name: postgres-{{- .Values.name -}}-admin
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
data:
  replicator: "cmVwbGljYXRvcg=="
  replicator-password: "cmVwbGljYXRvcg=="
  superuser: "cG9zdGdyZXM="
  superuser-password: "cG9zdGdyZXM="