apiVersion: v1
kind: Secret
metadata:
  name: postgres-{{- .Values.name -}}-write
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
data:
  host: "base64"
  port: "NTQzMg=="
  user: "Y2xpZW50"
  password: "Y2xpZW50"