apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-{{- .Values.name -}}-role
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints","pods","services"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]