{{- if and .Values.backup.enable .Values.backup.cronjob }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-{{- .Values.name }}-walg
  namespace: {{ .Values.namespace }}
  labels:
    backup: "true"
    walg: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-backup-{{- .Values.name -}}-role
  namespace: {{ .Values.namespace }}
  labels:
    backup: "true"
    walg: "true"
rules:
  - apiGroups: [""]
    resources: ["endpoints","pods","services", "pods/exec"]
    verbs: ["get", "list", "patch", "update", "watch", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-backup-{{- .Values.name -}}-walg-rolebind
  namespace: {{ .Values.namespace }}
  labels:
    backup: "true"
    walg: "true"
roleRef:
  kind: Role
  name: postgres-backup-{{- .Values.name -}}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: postgres-backup-{{- .Values.name }}-walg
    namespace: {{ .Values.namespace }}
{{- end }}