apiVersion: v1
data:
  pg_hba.conf: |+

    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    {{- if .Values.config.hba }}
    {{- range .Values.config.hba }}
    {{ . }}
    {{- end }}
    {{- end }}
    host    all             all             0.0.0.0/0               md5
    host    replication    replicator       0.0.0.0/0               md5

kind: ConfigMap
metadata:
  name: postgres-{{- .Values.name -}}-pghba-config
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
