{{- if .Values.backup.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-{{- .Values.name -}}-walg-config
  namespace: {{ .Values.namespace }}
  labels:
{{- include "postgres-labels" . | indent 4 }}
data:
  walg.json: |-
    {
      "WALG_DELTA_MAX_STEPS": "0",
      "WALG_UPLOAD_DISK_CONCURRENCY": "2",
      {{- if eq .Values.backup.platform.name "gcp" }}
      "WALG_GS_PREFIX": "{{- .Values.backup.platform.bucketName | default "gs://my-bucket" -}}",
      "GOOGLE_APPLICATION_CREDENTIALS": "/home/postgres/s3key/{{- .Values.backup.platform.secret.key -}}"
      {{- end }}
    }
{{- end }}