namespace: default
name: my-test
version: "14"
labels: {}
  #key: val
secrets: {}
  #superuser_password: pass #echo -n "anyPassword" | base64
  #replicator_password: pass #echo -n "anyPassword" | base64
client:
 # name: #echo -n "clientName" | base64
 # password:  #echo -n "clientpass" | base64
 # database: my_database_name #echo -n "clientdatabase" | base64      without '-' (test-test)  its not correct for postgres
storageclass: {}
replicas: 1
resources:
  request:
    cpu: 500m
    memory: 1048Mi
  limit:
    cpu: 1000m
    memory: 2048Mi
storage:
  capacity: 5Gi

sidecar:
  enable: false
  resources:
    request:
      cpu: 50m
      memory: 78Mi
    limit:
      cpu: 100m
      memory: 148Mi

backup:
  enable: false
