namespace: default
name: my-test
version: "14"
labels: {}
  #key: val
imagePullSecrets: {}
  #- secretname
secrets: {}
  #superuser_password: pass #echo -n "anyPassword" | base64
  #replicator_password: pass #echo -n "anyPassword" | base64
client:
  name: c3Rhcg== #echo -n "clientName" | base64    (name must not be equal 'user')
  password: d2Fycw== #echo -n "clientpass" | base64
  database: bXlfZGF0YWJhc2VfdGVzdA== ## my_database_name #echo -n "clientdatabase" | base64      without '-' (test-test)  its not correct for postgres

storageclass: {}
replicas: 1
resources:
  request:
    cpu: 500m
    memory: 1048Mi
  limit:
    cpu: 1000m
    memory: 2048Mi
storage:
  capacity: 5Gi

sidecar:
  enable: false
  resources:
    request:
      cpu: 50m
      memory: 78Mi
    limit:
      cpu: 100m
      memory: 148Mi

backup:
  enable: false
  platform:
    name: gcp #aws #azure #bare metal #gcp
    #there you must create secret for s3 backup for gcp
    secret:
      name: secret #your secret name  kubectl create  secret generic -n namespace secretname --from-file=key.json 
      key: key.json
    bucketName: gs://my-custom-bucket

config:
  hba: {}
    #- host databasename  username      ip (0.0.0.0/0)  md5 or trust